"""Workflow orchestration service.

Composes the deterministic state machine with application handlers and the AI
components. Workflows are built from the approved knowledge templates (required
documents, deterministic rules, state diagrams), not generated by an LLM. The AI
provider is strictly an *advisory* layer: it can flag warnings that prompt a
human review, but it can never reverse a deterministic block.
"""

from __future__ import annotations

import logging
import threading
import uuid
from datetime import datetime, timezone
from itertools import count
from typing import Any, Optional

from ..ai.llm_provider import LLMProvider
from ..core.config import Settings
from ..core.observability import log_event
from ..models.api import AdvanceWorkflowRequest, WorkflowDetailResponse, WorkflowProgress
from ..models.audit import AuditEvent
from ..models.document import DocumentRecord, ExtractedField
from ..models.enums import (
    AuditEventType,
    StateStatus,
    StateType,
    ValidationStatus,
    WorkflowStatus,
)
from ..models.workflow import State, Transition, Workflow
from ..rules.engine import validate_application
from ..services.catalog import ServiceCatalog
from ..services.demo_scenario import DEMO_PROFILE
from ..services.document_service import DocumentService
from ..storage.repository import WorkflowRepository
from ..workflow.errors import WorkflowNotFound
from ..workflow.state_machine import (
    AdvanceResult,
    ExecutionContext,
    StepHandlerMap,
    StepResult,
    advance_workflow,
    needs_label,
)

logger = logging.getLogger(__name__)

_TERMINAL_STATUSES = frozenset(
    {
        WorkflowStatus.COMPLETED,
        WorkflowStatus.CANCELLED,
        WorkflowStatus.BLOCKED,
        WorkflowStatus.FAILED,
        WorkflowStatus.GENERATION_FAILED,
    }
)

_TEMPLATE_TERMINAL = "terminal"


class WorkflowService:
    def __init__(
        self,
        repo: WorkflowRepository,
        generator,
        llm: LLMProvider,
        settings: Settings,
        catalog: ServiceCatalog,
        document_service: Optional[DocumentService] = None,
        purge_documents_on_completion: bool = True,
    ) -> None:
        self._repo = repo
        self._llm = llm
        self._settings = settings
        self._catalog = catalog
        self._document_service = document_service
        self._purge_documents_on_completion = purge_documents_on_completion

    # ------------------------------------------------------------------ create

    def create_workflow(self, goal: str) -> Workflow:
        workflow_id = f"wf_{uuid.uuid4().hex[:12]}"
        self._repo.append_audit(
            AuditEvent(workflow_id=workflow_id, event_type=AuditEventType.WORKFLOW_CREATED, details={"goal": goal})
        )
        service = self._catalog.match(goal)
        workflow = self._workflow_from_template(service, workflow_id, goal)
        self._repo.append_audit(
            AuditEvent(
                workflow_id=workflow_id,
                event_type=AuditEventType.WORKFLOW_GENERATED,
                details={
                    "states": len(workflow.states),
                    "service": service["id"],
                    "planner": "knowledge-template",
                },
            )
        )
        self._repo.save_workflow(workflow)
        return workflow

    def _workflow_from_template(self, service: dict[str, Any], workflow_id: str, goal: str) -> Workflow:
        tmpl = service["workflow"]
        states = [
            State(
                id=s["id"],
                label=s["label"],
                type=StateType(s["type"]),
                description=s.get("description", ""),
                required_documents=list(s.get("required_documents", [])),
                transitions=[
                    Transition(target=t["target"], condition=t["condition"])
                    for t in s.get("transitions", [])
                ],
            )
            for s in tmpl["states"]
        ]
        terminal_states = list(tmpl.get("terminal_states", []))
        if not terminal_states:
            terminal_states = [s["id"] for s in tmpl["states"] if s.get("type") == _TEMPLATE_TERMINAL]
        return Workflow(
            workflow_id=workflow_id,
            goal=goal or service["name"],
            initial_state=tmpl["initial_state"],
            terminal_states=terminal_states,
            states=states,
            status=WorkflowStatus.IN_PROGRESS,
            collected_data={"service_id": service["id"]},
        )

    # ------------------------------------------------------------------ read

    def get_workflow(self, workflow_id: str) -> Optional[Workflow]:
        return self._repo.get_workflow(workflow_id)

    def audit_event(
        self,
        workflow_id: str,
        event_type: AuditEventType,
        *,
        details: Optional[dict[str, Any]] = None,
        confidence: Optional[float] = None,
    ) -> AuditEvent:
        return AuditEvent(
            workflow_id=workflow_id,
            event_type=event_type,
            details=details or {},
            confidence=confidence,
        )

    def to_detail(self, workflow: Workflow) -> WorkflowDetailResponse:
        active = next((s for s in workflow.states if s.status == StateStatus.ACTIVE), None)
        completed = sum(1 for s in workflow.states if s.status in {StateStatus.COMPLETED})
        total = max(1, len(workflow.states))
        has_warning = any(s.status == StateStatus.WARNING for s in workflow.states)
        docs = {
            d.classification: d
            for d in self._repo.list_documents(workflow.workflow_id)
            if d.classification
        }

        validation = workflow.collected_data.get("validation_result")
        submission = workflow.collected_data.get("submission_result")

        return WorkflowDetailResponse(
            workflow_id=workflow.workflow_id,
            status=workflow.status,
            goal=workflow.goal,
            current_state=active.id if active else workflow.current_state,
            last_message=_message(active, workflow, docs, has_warning),
            needs=needs_label(active) if active else None,
            progress=WorkflowProgress(completed=completed, total=total, ratio=completed / total),
            states=[s.model_dump() for s in workflow.states],
            collected_documents=sorted(docs),
            validation=validation,
            submission=submission,
        )

    # ----------------------------------------------------------------- advance

    def advance(self, workflow_id: str, inputs: Optional[AdvanceWorkflowRequest] = None) -> AdvanceResult:
        workflow = self._repo.get_workflow(workflow_id)
        if workflow is None:
            raise WorkflowNotFound(f"workflow '{workflow_id}' not found")
        ctx = self._build_context(workflow, inputs)
        handlers = self._build_handlers(workflow)
        result = advance_workflow(workflow, handlers, ctx, inputs)
        validation_result = ctx.results.get(_validation_state_id(workflow))
        if validation_result:
            workflow.collected_data["validation_result"] = validation_result
            workflow.collected_data["validation_status"] = validation_result.get("status")
        # Persist the execution receipt: a cold start must not lose the confirmation id.
        for state in workflow.states:
            if state.type == StateType.EXECUTION and state.id in ctx.results:
                package = ctx.results[state.id].get("package")
                if package:
                    workflow.collected_data["submission_result"] = package
        for event in result.events:
            self._repo.append_audit(event)

            log_event(
                "workflow_execution_event",
                workflow_id=workflow_id,
                event_type=getattr(event.event_type, "value", str(event.event_type)),
                from_state=event.from_state,
                to_state=event.to_state,
            )

        self._repo.save_workflow(workflow)

        if self._purge_documents_on_completion and workflow.status in _TERMINAL_STATUSES:
            self._purge_documents(workflow)

        if workflow.status == WorkflowStatus.COMPLETED:
            log_event(
                "workflow_completed",
                workflow_id=workflow_id,
                current_state=workflow.current_state,
            )

        return result

    def _purge_documents(self, workflow: Workflow) -> None:
        """Fire the document-retention callback for a terminal workflow.

        Deletes stored bytes (best-effort) and records a `documents_purged`
        audit event so retention is observable. Blocked and cancelled workflows
        keep their documents for review; only finished ones purge.
        """
        if self._document_service is None:
            return
        if workflow.status != WorkflowStatus.COMPLETED:
            logger.info(
                "retaining documents for workflow %s (status=%s)",
                workflow.workflow_id,
                workflow.status.value,
            )
            return
        purged = self._document_service.purge_workflow_documents(workflow.workflow_id)
        self._repo.append_audit(
            AuditEvent(
                workflow_id=workflow.workflow_id,
                event_type=AuditEventType.DOCUMENTS_PURGED,
                details={"purged_count": purged, "status": workflow.status.value},
            )
        )
        log_event(
            "documents_purged",
            workflow_id=workflow.workflow_id,
            purged_count=purged,
            status=workflow.status.value,
        )

    # ------------------------------------------------------------- internals

    def _build_context(
        self, workflow: Workflow, inputs: Optional[AdvanceWorkflowRequest] = None
    ) -> ExecutionContext:
        docs = self._repo.list_documents(workflow.workflow_id)
        collected = {d.classification: d for d in docs if d.classification}
        data: dict[str, Any] = dict(workflow.collected_data)

        if inputs and inputs.user_input:
            if "profile" in inputs.user_input and isinstance(inputs.user_input["profile"], dict):
                data["profile"] = {**data.get("profile", {}), **inputs.user_input["profile"]}
            else:
                provided = {k: v for k, v in inputs.user_input.items() if isinstance(v, (str, int, float, bool))}
                if provided:
                    data["profile"] = {**data.get("profile", {}), **provided}
            if "profile" in data:
                workflow.collected_data["profile"] = data["profile"]

        if not data.get("profile"):
            data["profile"] = DEMO_PROFILE if self._settings.demo_mode else {}
        return ExecutionContext(data=data, collected_documents=collected, results={})

    def _build_handlers(self, workflow: Workflow) -> StepHandlerMap:
        service_id = workflow.collected_data.get("service_id") or self._catalog.default_service()["id"]
        service = self._catalog.get_service(service_id)
        handlers: StepHandlerMap = {}
        for state in workflow.states:
            if state.type == StateType.VALIDATION:
                handlers[state.id] = _validation_handler(self._llm, self._settings, self._catalog, service)
            elif state.type == StateType.EXECUTION:
                handlers[state.id] = _submission_handler()
            elif state.type == StateType.AUTOMATIC:
                # Templates have no automatic states; a no-op keeps future
                # templates safe without an LLM in the execute path.
                handlers[state.id] = _noop_handler()
        return handlers


# ------------------------------------------------------------------ handlers


def _noop_handler() -> Any:
    def execute(state: State, ctx: ExecutionContext) -> StepResult:
        return StepResult(status="completed", confidence=1.0, data={"ok": True})

    return execute


def _validation_handler(llm: LLMProvider, settings: Settings, catalog: ServiceCatalog, service: dict[str, Any]) -> Any:
    doc_types = catalog.doc_types()

    def execute(state: State, ctx: ExecutionContext) -> StepResult:
        result = validate_application(service, doc_types, ctx.collected_documents)

        status = result.status
        issues = list(result.issues)
        advisory = llm.run_cross_validation(
            service.get("process", {}).get("requirements", []),
            _extracted_of(ctx.collected_documents),
        )

        # The advisory may add warnings (-> needs review) but can never weaken a
        # deterministic block, upgrade a block, or invent evidence.
        if status is ValidationStatus.PASS and advisory.status == ValidationStatus.NEEDS_REVIEW:
            status = ValidationStatus.NEEDS_REVIEW
        if status is not ValidationStatus.BLOCK and advisory.confidence < settings.confidence_pass:
            status = ValidationStatus.NEEDS_REVIEW
        if status is not ValidationStatus.BLOCK:
            for issue in advisory.issues:
                if not any(existing.message == issue.message for existing in issues):
                    issues.append(issue)

        confidence = min(result.confidence, advisory.confidence)
        payload = {
            "status": status.value,
            "confidence": confidence,
            "issues": [i.model_dump() for i in issues],
            "suggestions": [i.suggestion for i in issues if i.suggestion],
            "checked_documents": sorted(set(result.checked_documents) | set(advisory.checked_documents)),
        }
        ctx.data["validation_status"] = status.value
        return StepResult(status="completed", confidence=confidence, data=payload)

    return execute


def _submission_handler() -> Any:
    def execute(state: State, ctx: ExecutionContext) -> StepResult:
        confirmation_id = _next_confirmation_id()
        package = {
            "confirmation_id": confirmation_id,
            "documents": sorted(ctx.collected_documents),
            "eligible": ctx.data.get("validation_status") == "pass",
            "submitted_at": _now(),
            "simulated": True,
        }
        return StepResult(
            status="completed",
            confidence=1.0,
            data={"submitted": True, "package": package},
        )

    return execute


_confirmation_counter = count(2026001)
_confirmation_lock = threading.Lock()


def _next_confirmation_id() -> str:
    """Monotonic, thread-safe confirmation id (e.g. ``FF-2026002``)."""
    with _confirmation_lock:
        return f"FF-{next(_confirmation_counter)}"


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _extracted_of(collected: dict[str, Any]) -> dict[str, dict[str, ExtractedField]]:
    extracted: dict[str, dict[str, ExtractedField]] = {}
    for classification, doc in collected.items():
        if isinstance(doc, DocumentRecord) and getattr(doc, "extracted_fields", None):
            extracted[classification] = dict(doc.extracted_fields)
    return extracted


def _validation_state_id(workflow: Workflow) -> Optional[str]:
    for s in workflow.states:
        if s.type == StateType.VALIDATION:
            return s.id
    return None


def _message(
    active: Optional[State],
    workflow: Workflow,
    docs: dict[str, DocumentRecord],
    has_warning: bool,
) -> Optional[str]:
    if workflow.status == WorkflowStatus.COMPLETED:
        return "Application ready — the reviewed submission is assembled for hand-off."
    if workflow.status == WorkflowStatus.CANCELLED:
        return "Submission declined. Workflow ended."
    if workflow.status == WorkflowStatus.BLOCKED:
        return "Submission blocked: a hard requirement was not met. The application was NOT submitted."
    if workflow.status == WorkflowStatus.FAILED:
        return "The workflow failed and needs review."
    if active is None:
        return "Ready to begin."
    if active.type == StateType.DOCUMENT_REQUIRED:
        missing = [d for d in active.required_documents if d not in docs]
        if missing:
            return f"Upload required documents: {', '.join(missing)}."
        return "All required documents received."
    if active.type == StateType.HUMAN_APPROVAL:
        return "This action requires your explicit approval."
    if active.type == StateType.USER_INPUT:
        return active.description
    return active.description
